version: '3.8'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://db/test_database
    depends_on:
      - db
  input_service:
    build: .
    command: python3 input_service.py
    environment:
      - DATABASE_URL=mongodb://db/test_database
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
